# Name and version of this dbt project.
name: 'devkit_connector'
version: '0.1.1'
require-dbt-version: [">=1.0.0", "<2.0.0"]
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'devkit_connector'

vars:
   # Name of the schema where the raw input data is stored.
  schema_sources: "devkit_connector"
  # Configuration to use pm-utils package.
  date_format: 23 # SQL Server: 23, Snowflake: 'YYYY-MM-DD'
  time_format: 8 # SQL Server: 8, Snowflake: 'hh24:mi:ss'
  datetime_format: 20 # SQL Server: 20, Snowflake: 'YYYY-MM-DD hh24:mi:ss.ff3'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
macro-paths: ["macros"]

# Directory which will store compiled SQL files and will be removed by 'dbt clean'.
target-path: "target"
clean-targets:
  - "target"

# All models are materialized as tables by default.
models:
  +materialized: table

# Quoting is enabled for databases, schemas, and identifiers.
quoting:
  database: true
  schema: true
  identifier: true
